# Generated by Django 4.1.7 on 2023-05-16 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie_app', '0007_alter_movie_currency'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='currency',
            field=models.CharField(choices=[('E', 'Euro'), ('U', 'Dollar-US'), ('R', 'Rubles')], default='U', max_length=1),
        ),
    ]
