# Generated by Django 4.1.7 on 2023-05-18 12:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movie_app', '0018_director_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='director',
            name='slug',
        ),
    ]
