# Generated by Django 4.1.7 on 2023-05-19 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie_app', '0027_alter_movie_director'),
    ]

    operations = [
        migrations.CreateModel(
            name='DressingRoom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('floor', models.IntegerField(blank=True)),
                ('number_room', models.IntegerField(blank=True)),
            ],
        ),
    ]
