# Generated by Django 4.1.7 on 2023-05-19 11:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('movie_app', '0028_dressingroom'),
    ]

    operations = [
        migrations.AddField(
            model_name='actor',
            name='dresing',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='movie_app.dressingroom'),
        ),
    ]
