# Generated by Django 4.1.7 on 2023-04-14 009:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('advertisement', '0006_advertisementtype_advertisement_type'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='advertisement',
            table='advertisements',
        ),
    ]
