# Generated by Django 4.1.7 on 2023-04-14 009:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('advertisement', '0007_alter_advertisement_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='advertisementstatus',
            table='status',
        ),
        migrations.AlterModelTable(
            name='advertisementtype',
            table='type',
        ),
    ]
