# Generated by Django 4.1.7 on 2023-05-16 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie_app', '0005_alter_movie_year'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='currency',
            field=models.CharField(choices=[('EUR', 'Euro'), ('USD', 'Dollar-US'), ('RUB', 'Rubles')], default='USD', max_length=3),
        ),
    ]
